workflows:
  ios-app-store:
    name: iOS App Store Release
    environment:
      flutter: stable
      xcode: latest
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.example.agilizadorRmApp
      groups:
        - ios_credentials
    scripts:
      - name: Obtener dependencias de Flutter
        script: flutter packages pub get
      
      - name: Compilar iOS para App Store
        script: |
          flutter clean
          flutter pub get
          flutter build ipa --release  # <-- Sin --no-codesign
    
    artifacts:
      - build/ios/ipa/*.ipa
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_API_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true