name: agilizador_rm_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Networking & API
  http: ^1.6.0
  url_launcher: ^6.3.2
  
  # Internationalization & Utils
  intl: ^0.20.2
  share_plus: ^12.0.1
  
  # Storage & Preferences
  shared_preferences: ^2.5.5
  path_provider: ^2.1.5
  
  # Image Handling
  image_picker: ^1.2.1
  flutter_image_compress: ^2.3.0  # <-- NUEVO: Compresión de imágenes
  
  # File & Documents
  file_picker: ^10.3.10
  open_filex: ^4.7.0
  
  # Maps & Location
  flutter_map: ^8.2.2
  latlong2: ^0.9.1
  
  # Security & Auth
  local_auth: ^3.0.1
  
  # Grid Views
  reorderable_grid_view: ^2.2.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/asesores-rm-new-white.webp
    - assets/documentos/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_app.png"